DELIMITER $$

CREATE TRIGGER validate_ecriture
BEFORE INSERT ON ECRITURES_COMPTABLES
FOR EACH ROW
BEGIN
    IF NEW.compte_debite_id IS NULL OR NEW.compte_credite_id IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Comptes invalides';
    END IF;
END $$

DELIMITER ;
